export const MockDBsmall =[
    {
        "ProductId": 42419,
        "Gender": "Girls",
        "Category": "Apparel",
        "SubCategory": "Topwear",
        "description": "Tops",
        "Colour": "White",
        "Usage": "Casual",
        "title": "Gini and Jony Girls Knit White Top",
        "Image": "42419.jpg",
        "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/f3964f76c78edd85f4512d98b26d52e9_images.jpg",
        "price": 2781.66
    },
    {
        "ProductId": 34009,
        "Gender": "Girls",
        "Category": "Apparel",
        "SubCategory": "Topwear",
        "description": "Tops",
        "Colour": "Black",
        "Usage": "Casual",
        "title": "Gini and Jony Girls Black Top",
        "Image": "34009.jpg",
        "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/dce310e4c15223a6c964631190263284_images.jpg",
        "price": 2364.07
    },
    {
        "ProductId": 40143,
        "Gender": "Girls",
        "Category": "Apparel",
        "SubCategory": "Topwear",
        "description": "Tops",
        "Colour": "Blue",
        "Usage": "Casual",
        "title": "Gini and Jony Girls Pretty Blossom Blue Top",
        "Image": "40143.jpg",
        "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/fc3c1b46906d5c148c45f532d0b3ffb5_images.jpg",
        "price": 1077.78
    },
    {
        "ProductId": 23623,
        "Gender": "Girls",
        "Category": "Apparel",
        "SubCategory": "Topwear",
        "description": "Tops",
        "Colour": "Pink",
        "Usage": "Casual",
        "title": "Doodle Kids Girls Pink I love Shopping Top",
        "Image": "23623.jpg",
        "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/ef9685293a987f515492addd034006bf_images.jpg",
        "price": 2848.52
    },
    {
        "ProductId": 25520,
        "Gender": "Girls",
        "Category": "Apparel",
        "SubCategory": "Topwear",
        "description": "Tops",
        "Colour": "White",
        "Usage": "Casual",
        "title": "Doodle Kids Girls City Chic White Top",
        "Image": "25520.jpg",
        "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/416f7bd57546242fd72a817de0d517e5_images.jpg",
        "price": 2848.74
    },
    {
        "ProductId": 31120,
        "Gender": "Girls",
        "Category": "Apparel",
        "SubCategory": "Topwear",
        "description": "Tops",
        "Colour": "Pink",
        "Usage": "Casual",
        "title": "Palm Tree Girls Pink Top",
        "Image": "31120.jpg",
        "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/83f4ab34db71459ba1f80bb8992cf9d5_images.jpg",
        "price": 1679.37
    },
  ];