export const MockDB =[
  {
      "ProductId": 42419,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "White",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Knit White Top",
      "Image": "42419.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/f3964f76c78edd85f4512d98b26d52e9_images.jpg",
      "price": 2781.66
  },
  {
      "ProductId": 34009,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "Black",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Black Top",
      "Image": "34009.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/dce310e4c15223a6c964631190263284_images.jpg",
      "price": 2364.07
  },
  {
      "ProductId": 40143,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Pretty Blossom Blue Top",
      "Image": "40143.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/fc3c1b46906d5c148c45f532d0b3ffb5_images.jpg",
      "price": 1077.78
  },
  {
      "ProductId": 23623,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Doodle Kids Girls Pink I love Shopping Top",
      "Image": "23623.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/ef9685293a987f515492addd034006bf_images.jpg",
      "price": 2848.52
  },
  {
      "ProductId": 25520,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "White",
      "Usage": "Casual",
      "title": "Doodle Kids Girls City Chic White Top",
      "Image": "25520.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/416f7bd57546242fd72a817de0d517e5_images.jpg",
      "price": 2848.74
  },
  {
      "ProductId": 31120,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Palm Tree Girls Pink Top",
      "Image": "31120.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/83f4ab34db71459ba1f80bb8992cf9d5_images.jpg",
      "price": 1679.37
  },
  {
      "ProductId": 31118,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "Red",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Red Top",
      "Image": "31118.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/1e3b40d501f5fbbceeab3879db474932_images.jpg",
      "price": 2759.19
  },
  {
      "ProductId": 40144,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Pretty Blossom Pink Top",
      "Image": "40144.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/1397081a5a637d539b0197aae4a6855e_images.jpg",
      "price": 2825.71
  },
  {
      "ProductId": 23624,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tops",
      "Colour": "White",
      "Usage": "Casual",
      "title": "Doodle Kids Girls White I love Shopping Top",
      "Image": "23624.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/5ab7fb83e0891f3453746c9a073e3ec6_images.jpg",
      "price": 1824.51
  },
  {
      "ProductId": 4718,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "Yellow",
      "Usage": "Casual",
      "title": "Disney Kids Girl's Summer Fun Fair Yellow Teen Kidswear",
      "Image": "4718.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/1109685531795f17aca2acaba2ab39ad_images.jpg",
      "price": 1175.75
  },
  {
      "ProductId": 47154,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Capris",
      "Colour": "Black",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Black Capris",
      "Image": "47154.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/5158808a5bdd60c8c8af6999f8481160_images.jpg",
      "price": 2669.63
  },
  {
      "ProductId": 54923,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Capris",
      "Colour": "Olive",
      "Usage": "Casual",
      "title": "Do u speak Green Girls Olive 3\\/4 Pant",
      "Image": "54923.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/Do-u-speak-Green-Girls-Olive-34-Pant_62311570aeebd7385030de554584a065_images.jpg",
      "price": 2576.83
  },
  {
      "ProductId": 47153,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Capris",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Pink Capris",
      "Image": "47153.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/87321ab7962a30b2e9b01fa16997029c_images.jpg",
      "price": 2416.57
  },
  {
      "ProductId": 34693,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Allen Solly Kids Girls Poplin Pink Shorts",
      "Image": "34693.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/c8c6fd3233823726f484da6b7007f016_images.jpg",
      "price": 1412.81
  },
  {
      "ProductId": 33271,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Skirts",
      "Colour": "Red",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Red Skirt",
      "Image": "33271.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/87725859164f90b1c366659f2f381238_images.jpg",
      "price": 2094.59
  },
  {
      "ProductId": 41007,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Navy Blue",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Woven Navy Blue Shorts",
      "Image": "41007.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/7195b148c3b6b41cf4ad730cbe7abbcb_images.jpg",
      "price": 1750.1
  },
  {
      "ProductId": 46813,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Skirts",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Pink Skirt",
      "Image": "46813.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/167c8880c4c77718ac8e2ecdf57e619c_images.jpg",
      "price": 2287.83
  },
  {
      "ProductId": 41000,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Woven Blue Shorts",
      "Image": "41000.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/4882420c3607228a30540b5b99aba1d4_images.jpg",
      "price": 2293.55
  },
  {
      "ProductId": 39328,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Green",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Green Shorts",
      "Image": "39328.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/7ed1ca17fdfdefdd6320156fe7ea7292_images.jpg",
      "price": 1840.91
  },
  {
      "ProductId": 46814,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Skirts",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Pink Skirt",
      "Image": "46814.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/4e26ee06c517e6f227ca6af3653f0f6b_images.jpg",
      "price": 1484.44
  },
  {
      "ProductId": 31127,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Black",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Black Dress",
      "Image": "31127.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/1f7c87ee0ac12c35df8c1dd28e2cd692_images.jpg",
      "price": 1253.21
  },
  {
      "ProductId": 36750,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Navy Blue",
      "Usage": "Casual",
      "title": "Little Miss Girls Chatterbox Navy Blue Dress",
      "Image": "36750.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/0d3b2725d327a275c52c6f999e3982eb_images.jpg",
      "price": 2456.8
  },
  {
      "ProductId": 31129,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Magenta",
      "Usage": "Casual",
      "title": "Giny and Jony Girls Printed White & Pink Dress",
      "Image": "31129.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/3a4faa7c017c3ea1e8df9c887b929d50_images.jpg",
      "price": 2922.46
  },
  {
      "ProductId": 50723,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Doodle Girls Blue Printed Dress",
      "Image": "50723.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/9fa6bd6c5b841804bdee04460ee934de_images.jpg",
      "price": 1868.69
  },
  {
      "ProductId": 50724,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Doodle Girls Blue Washed Dress",
      "Image": "50724.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/8f184224331047aa5fc5b0041b04dc53_images.jpg",
      "price": 2214.46
  },
  {
      "ProductId": 34065,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Black",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Black Dress",
      "Image": "34065.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/f7b69b3f5edf05058f33e21ebe87275f_images.jpg",
      "price": 2204.87
  },
  {
      "ProductId": 34062,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Printed Pink Dress",
      "Image": "34062.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/6e4f3854eb7b77188e914ee94bce4758_images.jpg",
      "price": 2037.3
  },
  {
      "ProductId": 31128,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Printed Teal Dress",
      "Image": "31128.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/73bdd9b109c5648fb93b144ebc338f94_images.jpg",
      "price": 2338.84
  },
  {
      "ProductId": 31126,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "White",
      "Usage": "Casual",
      "title": "Gini and Jony Girls White Dress",
      "Image": "31126.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/97c4ba68f6dd479533fd38fa8224ebf9_images.jpg",
      "price": 1920.46
  },
  {
      "ProductId": 34063,
      "Gender": "Girls",
      "Category": "Apparel",
      "SubCategory": "Dress",
      "description": "Dresses",
      "Colour": "Pink",
      "Usage": "Casual",
      "title": "Gini and Jony Girls Printed Pink Dress",
      "Image": "34063.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/1c6f5c73e5094eedd4c405f6d9cb2e53_images.jpg",
      "price": 2369.57
  },
  {
      "ProductId": 4729,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "Green",
      "Usage": "Casual",
      "title": "Disney Kids Boy's Crew Sea Life Sialing Green Teen Kidswear",
      "Image": "4729.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/0108969213975af06095ff84a0ec0c72_images.jpg",
      "price": 1966.17
  },
  {
      "ProductId": 8322,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Doodle Boy's Route 66 Biker Blue Teen Kidswear",
      "Image": "8322.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/117451d5bf32c9ec341a6dfd0c28121a_images.jpg",
      "price": 1377.05
  },
  {
      "ProductId": 34036,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Shirts",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Palm Tree Boys Check Blue Shirt",
      "Image": "34036.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/17d5cdd77de6f87ee2451b98f3466d88_images.jpg",
      "price": 1446.83
  },
  {
      "ProductId": 8325,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "Yellow",
      "Usage": "Casual",
      "title": "Doodle Boy's Athletic 77 Dept Yellow Teen Kidswear",
      "Image": "8325.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/e046ebf7dbb7ae5d9dd7980c21d264ac_images.jpg",
      "price": 2335.41
  },
  {
      "ProductId": 40947,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "Red",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Core Red T-shirt",
      "Image": "40947.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/ecfcc90e4ae597955732adf2680b9fa3_images.jpg",
      "price": 1658.54
  },
  {
      "ProductId": 34031,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Shirts",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Check Blue Shirt",
      "Image": "34031.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/0f5f0082a3413804e4f2adc80d59a3bb_images.jpg",
      "price": 2253.07
  },
  {
      "ProductId": 40978,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "Red",
      "Usage": "Casual",
      "title": "Gini and Jony Boys United Red T-shirt",
      "Image": "40978.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/4fb51b6af9daa7d7e7b37a54ee98d6a8_images.jpg",
      "price": 1973.92
  },
  {
      "ProductId": 34038,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Shirts",
      "Colour": "Red",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Check Red Shirt",
      "Image": "34038.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/95b4fd12eab9acd511b805a11601c92c_images.jpg",
      "price": 2517.04
  },
  {
      "ProductId": 40985,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "White",
      "Usage": "Casual",
      "title": "Gini and Jony Boys United White T-shirt",
      "Image": "40985.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/9ba6a4c84ec057a0ccd9a1a559b16531_images.jpg",
      "price": 1599.86
  },
  {
      "ProductId": 10054,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Topwear",
      "description": "Tshirts",
      "Colour": "Blue",
      "Usage": "Sports",
      "title": "Reebok Kids Kkr Boy's Premium Blue Jerseys",
      "Image": "10054.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/dd87d19692f01880e34a6cf2b0bd9b22_images.jpg",
      "price": 2649.51
  },
  {
      "ProductId": 31111,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Jeans",
      "Colour": "Black",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Solid Black Jeans",
      "Image": "31111.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/50aba4c7dbee879034bee18e8fa647f1_images.jpg",
      "price": 2288.95
  },
  {
      "ProductId": 31116,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Grey",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Grey Shorts",
      "Image": "31116.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/ab13e5576f1a6b597ca99514da15fec6_images.jpg",
      "price": 1907.59
  },
  {
      "ProductId": 34054,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Capris",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Palm Tree Boys Washed Blue 3\\/4 Length Pants",
      "Image": "34054.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/4a2a1ce049f358b88f551bbe27fcdfdb_images.jpg",
      "price": 1370.84
  },
  {
      "ProductId": 29176,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Khaki",
      "Usage": "Casual",
      "title": "United Colors of Benetton Boys Khaki Shorts",
      "Image": "29176.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/0306ed2619dc70f26359986b5ed7a8a0_images.jpg",
      "price": 2106.56
  },
  {
      "ProductId": 34053,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Capris",
      "Colour": "Yellow",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Yellow 3\\/4 Length Pants",
      "Image": "34053.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/ed972b8708185e04d4cbbc475fee3bff_images.jpg",
      "price": 1827.11
  },
  {
      "ProductId": 40126,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "White",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Boxer White Shorts",
      "Image": "40126.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/ff9ba2b75d61b477c14fe698ae212314_images.jpg",
      "price": 1490.18
  },
  {
      "ProductId": 40925,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Jeans",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Comics Blue Jeans",
      "Image": "40925.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/6303d1b19005036148228a9f8ae5bbab_images.jpg",
      "price": 1722.25
  },
  {
      "ProductId": 30603,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Maroon",
      "Usage": "Sports",
      "title": "Nike Boys Basketball Red Shorts",
      "Image": "30603.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/fb545a86912235fbd568a93f7fb3f12d_images.jpg",
      "price": 1262.02
  },
  {
      "ProductId": 39745,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Blue",
      "Usage": "Casual",
      "title": "Gini Jony Boys Blue Shorts",
      "Image": "39745.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/bccf1b8ee74179b0b8465bcfdf80f46c_images.jpg",
      "price": 2718.99
  },
  {
      "ProductId": 39319,
      "Gender": "Boys",
      "Category": "Apparel",
      "SubCategory": "Bottomwear",
      "description": "Shorts",
      "Colour": "Beige",
      "Usage": "Casual",
      "title": "Gini and Jony Boys Beige Shorts",
      "Image": "39319.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/4ce9548aa8e6ee3e2bbfde35def4c973_images.jpg",
      "price": 1196.53
  },
  {
      "ProductId": 9204,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Casual Shoes",
      "Colour": "Black",
      "Usage": "Casual",
      "title": "Puma Men Future Cat Remix SF Black Casual Shoes",
      "Image": "9204.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/051d64772f1b38ff476fbf0a807f365a_images.jpg",
      "price": 2630.65
  },
  {
      "ProductId": 9036,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Formal Shoes",
      "Colour": "Black",
      "Usage": "Formal",
      "title": "Buckaroo Men Flores Black Formal Shoes",
      "Image": "9036.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/06edc2da9c6d103d299e5e8dafc5b6b9_images.jpg",
      "price": 1460.44
  },
  {
      "ProductId": 39988,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Casual Shoes",
      "Colour": "White",
      "Usage": "Casual",
      "title": "Gas Men Europa White Shoes",
      "Image": "39988.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/9c3d77147758ab10f12caf6184fe13ef_images.jpg",
      "price": 2774.91
  },
  {
      "ProductId": 3168,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Sports Shoes",
      "Colour": "White",
      "Usage": "Sports",
      "title": "Nike Men's Incinerate MSL White Blue Shoe",
      "Image": "3168.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/4eff2353c62ec8b7bca9fbbaf5996bd2_images.jpg",
      "price": 2112.73
  },
  {
      "ProductId": 10268,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Formal Shoes",
      "Colour": "Black",
      "Usage": "Formal",
      "title": "Clarks Men Hang Work Leather Black Formal Shoes",
      "Image": "10268.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/2976e4095e7b3ae2de99df54d2adeaaa_images.jpg",
      "price": 1539.39
  },
  {
      "ProductId": 59435,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Formal Shoes",
      "Colour": "Black",
      "Usage": "Formal",
      "title": "Arrow Men Black Formal Shoes",
      "Image": "59435.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/Arrow-Men-Black-Formal-Shoes_70a3c7c185338a5636c8c0e668829bb6_images.jpg",
      "price": 1806.94
  },
  {
      "ProductId": 22198,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Casual Shoes",
      "Colour": "Black",
      "Usage": "Casual",
      "title": "Timberland Men Black Casual Shoes",
      "Image": "22198.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/70e74ca34b3b534b19d6b006d5bfad0a_images.jpg",
      "price": 1661.05
  },
  {
      "ProductId": 29570,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Casual Shoes",
      "Colour": "Purple",
      "Usage": "Casual",
      "title": "Vans Men Classic Slip-On Purple & Black Shoes",
      "Image": "29570.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/49f884ddf4420d869ad143857d3bc33d_images.jpg",
      "price": 2612.38
  },
  {
      "ProductId": 6628,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Sports Shoes",
      "Colour": "White",
      "Usage": "Sports",
      "title": "ADIDAS Men's Lowell White Silver Shoe",
      "Image": "6628.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/0707b75d2d44e9cec9d27c944294ddbe_images.jpg",
      "price": 2308.81
  },
  {
      "ProductId": 26538,
      "Gender": "Men",
      "Category": "Footwear",
      "SubCategory": "Shoes",
      "description": "Casual Shoes",
      "Colour": "Red",
      "Usage": "Casual",
      "title": "ID Men Red Shoes",
      "Image": "26538.jpg",
      "imageUrl": "http:\\/\\/assets.myntassets.com\\/v1\\/images\\/style\\/properties\\/6a6ebc47eaf2fe034bcfd94060a285ba_images.jpg",
      "price": 1674.95
  }
];